ENH add initialize method for input loader
GalSim-developers/GalSim pull request #1163
Opened 2022-06-30 12:11 UTC by beckermr

This PR adds the `initialize` method for inputs. 

todo:

 - [x] make sure it solves my problem
 - [x] write a test

closes #1162

2022-06-30 12:25 UTC, beckermr commented
See https://github.com/LSSTDESC/seacliff/pull/4 for an example use case.

2022-06-30 17:21 UTC, beckermr commented
@rmjarvis This one is ready for review!

2022-06-30 19:09 UTC, rmjarvis requested changes
Looks good.  Just one request to add a test that checks this when there are two input objs being processed.

2022-06-30 20:21 UTC, rmjarvis commented
Code looks fine.  Just one thing I didn't notice the first time.  Could you please rebase this onto main, rather than releases/2.3 and redirect the target of the merge?  This is a feature addition, so it shouldn't really go on the 2.3 series.

2022-06-30 20:22 UTC, beckermr commented
Will rebase but need to brush up on my git fu unless you have a quick oneliner for me. :)

2022-06-30 20:27 UTC, rmjarvis commented
(I always forget how to do the upsteam thing for forked repos.  It's easier if you started from a branch in GalSim-developers.)

2022-06-30 20:31 UTC, beckermr commented
This worked for me: https://medium.com/@gabriellamedas/git-rebase-and-git-rebase-onto-a6a3f83f9cce

TL;DR

```
git rebase --onto main releases/2.3 init-input
```

Moved all commits on `init-input` ahead of `releases/2.3` to `main`.

2022-06-30 20:34 UTC, rmjarvis commented
Oh, right.  That rebases onto your forked main, which is fine if that's current with the upstream main.

2022-06-30 20:36 UTC, beckermr commented
Awesome. FYI I cannot merge this PR so you'll have to do it once the tests pass.

2022-06-30 20:37 UTC, rmjarvis commented on tests/test_config_input.py
> +# Copyright (c) 2012-2021 by the GalSim developers team on GitHub
```suggestion
# Copyright (c) 2012-2022 by the GalSim developers team on GitHub
```

2022-07-01 00:13 UTC, beckermr commented
This is ready to merge!

2022-07-01 06:11 UTC, merged