WIP fix tests for JAX-Galsim
GalSim-developers/GalSim pull request #1252
Opened 2023-10-15 14:01 UTC by beckermr

This PR has tests that need fixes for JAX-Galsim. I am opening it in draft mode so we can be sure to sync this up with galsim `main` as needed.

2023-10-15 14:06 UTC, beckermr commented
The commits here need to be rebased onto main I think.

2023-10-16 11:19 UTC, beckermr commented on tests/galsim_test_helpers.py
> +    "funcname",
```suggestion
```

2023-10-16 11:28 UTC, beckermr commented on tests/galsim_test_helpers.py
> +    "profile",
```suggestion
```

2023-11-27 02:11 UTC, beckermr commented on tests/test_random.py
> +if not hasattr(galsim, "_galsim"):
```suggestion
if hasattr(galsim, "_galsim"):
```

2023-11-27 21:32 UTC, beckermr reviewed
Putting extraneous changes back. IDK how these got in here.

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    """Check that some function raises a GalSimDeprecationWarning as a warning, but not an error."""
```suggestion
    """Check that some function raises a GalSimDeprecationWarning as a warning, but not an error.
"""
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    check_dep(galsim.GSParams, small_fraction_of_flux=1.0e-6)
```suggestion
    check_dep(galsim.GSParams, small_fraction_of_flux=1.e-6)
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
    atm = galsim.Atmosphere(screen_size=10.0, altitude=0, r0_500=0.15, suppress_warning=True)
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    real_gal_cat = "real_galaxy_catalog_23.5_example.fits"
```suggestion
    real_gal_dir = os.path.join('..','examples','data')
    real_gal_cat = 'real_galaxy_catalog_23.5_example.fits'
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
        dir=real_gal_dir, file_name=real_gal_cat, preload=True)
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    test_seed = 987654
```suggestion
    test_seed=987654
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    ), "Inconsistent noise variance from getNoise and getNoiseProperties"
```suggestion
    assert var_1==var_2,'Inconsistent noise variance from getNoise and getNoiseProperties'
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    npoints = 100
```suggestion
    npoints=100
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    rw = check_dep(galsim.RandomWalk, npoints, half_light_radius=hlr, rng=rng)
```suggestion
    rw=check_dep(galsim.RandomWalk, npoints, half_light_radius=hlr, rng=rng)
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    assert nobj == npoints, "expected %d objects, got %d" % (npoints, nobj)
```suggestion
    nobj=len(rw.points)
    assert nobj == npoints,"expected %d objects, got %d" % (npoints, nobj)
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    gsp = galsim.GSParams(xvalue_accuracy=1.0e-8, kvalue_accuracy=1.0e-8)
```suggestion
    gsp = galsim.GSParams(xvalue_accuracy=1.e-8, kvalue_accuracy=1.e-8)
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    rw3 = check_dep(galsim.RandomWalk, npoints, half_light_radius=hlr, rng=rng3)
```suggestion
    rw3=check_dep(galsim.RandomWalk, npoints, half_light_radius=hlr, rng=rng3)
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    im = galsim.ImageD(64, 64, scale=0.5)
```suggestion
    im = galsim.ImageD(64,64, scale=0.5)
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    npoints = 100
```suggestion
    npoints=100
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +        galsim.RandomWalk,
```suggestion
    rw2=check_dep(galsim.RandomWalk,
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
>          # just make sure str() works, don't require eval to give
```suggestion
        
        
        # just make sure str() works, don't require eval to give
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +        st = str(rw)
```suggestion
        st=str(rw)
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +    flux = np.pi
```suggestion
    hlr=2.0
    flux=np.pi
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +        "flux": flux,
```suggestion
        'type': 'RandomWalk',
        'npoints': 100,
        'half_light_radius': hlr,
        'flux': flux,
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +        },
```suggestion
        'type': 'RandomWalk',
        'npoints': 150,
        'profile': {
            'type': 'Exponential',
            'half_light_radius': hlr,
            'flux': flux,
        }
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +            "rng": galsim.BaseDeviate(31415),
```suggestion
        config={
            'gal': gal_config,
            'rng': galsim.BaseDeviate(31415),
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +        rwc = check_dep(galsim.config.BuildGSObject, config, "gal")[0]
```suggestion
        rwc = check_dep(galsim.config.BuildGSObject, config, 'gal')[0]
```

2023-11-27 21:32 UTC, beckermr commented on tests/test_deprecated.py
> +            gal_config["npoints"],
```suggestion
        rw = check_dep(galsim.RandomWalk,
            gal_config['npoints'],
```

2023-11-27 21:34 UTC, beckermr commented on tests/test_deprecated.py
> +    testfns = [v for k, v in vars().items() if k[:5] == "test_" and callable(v)]
```suggestion
    testfns = [v for k, v in vars().items() if k[:5] == 'test_' and callable(v)]
```

2023-11-27 21:35 UTC, beckermr commented on tests/test_deprecated.py
> +    sed = check_dep(getattr, PSF, "SED")
```suggestion
    sed = check_dep(getattr, PSF, 'SED')
```

2023-11-27 21:35 UTC, beckermr commented on tests/test_deprecated.py
> +    sed1 = check_dep(getattr, PSF1, "SED")
```suggestion
    sed1 = check_dep(getattr, PSF1, 'SED')
```

2023-11-27 21:36 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion
    sed2 = check_dep(getattr, mono_PSF, 'SED')
    assert sed1 == mono_PSF.sed == galsim.SED(1, 'nm', '1')
```

2023-11-27 21:36 UTC, beckermr commented on tests/test_deprecated.py
> +        "psf": {"type": "RomanPSF", "SCA": 4, "bandpass": "W149"},
```suggestion
        'modules': ['galsim.roman'],
        'psf': {'type': 'RomanPSF', 'SCA': 4, 'bandpass': 'W149'},
```

2023-11-27 21:37 UTC, beckermr commented on tests/test_deprecated.py
> +    print("psf2 = ", str(psf2))
```suggestion
    psf1 = check_dep(galsim.config.BuildGSObject, config, 'psf')[0]
    psf2 = check_dep(galsim.roman.getPSF, SCA=4, bandpass='W149')
    print('psf1 = ', str(psf1))
    print('psf2 = ', str(psf2))
```

2023-11-27 21:41 UTC, beckermr commented on tests/test_deprecated.py
> +        'psf': {'type': 'RomanPSF', 'SCA': 4, 'bandpass': 'W149'},
```suggestion
        'modules' : ['galsim.roman'],
        'psf' : { 'type' : 'RomanPSF', 'SCA': 4, 'bandpass': 'W149' },
```

2023-11-27 21:41 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
    PSF3 = check_dep(galsim.InterpolatedChromaticObject, PSF,
                     waves=np.linspace(bandpass.blue_limit, bandpass.red_limit, 30),
                     use_exact_SED=False)
```

2023-11-27 21:42 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
    PSF2 = check_dep(PSF.interpolate,
                     waves=np.linspace(bandpass.blue_limit, bandpass.red_limit, 30),
                     use_exact_SED=False)
```

2023-11-27 21:43 UTC, beckermr commented on tests/test_deprecated.py
> +        'psf' : { 'type' : 'RomanPSF', 'SCA': 4, 'bandpass': 'W149' },
```suggestion
        'psf' : { 'type' : 'RomanPSF', 'SCA': 4, 'bandpass': 'W149' }
```

2023-11-27 21:44 UTC, beckermr commented on tests/test_deprecated.py
> +"""
```suggestion
    """
```

2023-11-27 21:45 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion
    assert cf_1==cf_2, 'Inconsistent noise properties from getNoise and getNoiseProperties'
```

2023-11-27 21:46 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
    ii = galsim.InterpolatedImage(im_2, normalization='sb', calculate_stepk=False,
        calculate_maxk=False, x_interpolant='linear')
    cf_2 = check_dep(galsim.correlatednoise._BaseCorrelatedNoise,
                     galsim.BaseDeviate(test_seed), ii, im_2.wcs)
```

2023-11-27 21:46 UTC, beckermr commented on tests/test_deprecated.py
> +    assert rw.npoints == npoints, "expected npoints==%d, got %d" % (npoints, rw.npoints)
```suggestion
    assert rw.npoints==npoints,"expected npoints==%d, got %d" % (npoints, rw.npoints)
```

2023-11-27 21:48 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
    assert rw.input_half_light_radius==hlr,\
        "expected hlr==%g, got %g" % (hlr, rw.input_half_light_radius)
```

2023-11-27 21:49 UTC, beckermr commented on tests/test_deprecated.py
> +        calculate_maxk=False, x_interpolant='linear')
```suggestion
                                  calculate_maxk=False, x_interpolant='linear')
```

2023-11-27 21:50 UTC, beckermr commented on tests/test_deprecated.py
> +    assert cf_1==cf_2, 'Inconsistent noise properties from getNoise and getNoiseProperties'
```suggestion
    assert cf_1==cf_2,'Inconsistent noise properties from getNoise and getNoiseProperties'
```

2023-11-27 21:50 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
    pts=rw.points
    assert pts.shape == (npoints, 2),"expected (%d,2) shape for points, got %s" % (npoints, pts.shape)
```

2023-11-27 21:51 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
    rw2 = check_dep(galsim.RandomWalk, npoints, half_light_radius=hlr, rng=rng2, gsparams=gsp)
```

2023-11-27 21:51 UTC, beckermr commented on tests/test_deprecated.py
> +        galsim.RandomWalk,
```suggestion
    flux=1
    rw1=check_dep(galsim.RandomWalk,
```

2023-11-27 21:51 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion


```

2023-11-27 21:52 UTC, beckermr commented on tests/test_deprecated.py
> +        'flux': flux,
```suggestion
        'type':'RandomWalk',
        'npoints':100,
        'half_light_radius':hlr,
        'flux':flux,
```

2023-11-27 21:53 UTC, beckermr commented on tests/test_deprecated.py
> +            'rng': galsim.BaseDeviate(31415),
```suggestion
            'gal':gal_config,
            'rng':galsim.BaseDeviate(31415),
```

2023-11-27 21:54 UTC, beckermr commented on tests/test_deprecated.py
> +    cubic_v = Cubic(-3.7e-5, 2000.0, 'v')
```suggestion
    cubic_u = Cubic(2.9e-5, 2000., 'u')
    cubic_v = Cubic(-3.7e-5, 2000., 'v')
```

2023-11-27 21:54 UTC, beckermr commented on tests/test_deprecated.py
> +    """Test that the deprecated wfirst module works like the new roman module."""
```suggestion
    """Test that the deprecated wfirst module works like the new roman module.
    """
```

2023-11-27 21:55 UTC, beckermr commented on tests/test_deprecated.py
> +                           use_exact_sed=False)
```suggestion
                          use_exact_sed=False)
```

2023-11-27 21:56 UTC, beckermr commented on tests/test_deprecated.py
> +    bulge_SED = galsim.SED("CWW_E_ext.sed", wave_type="ang", flux_type="flambda")
```suggestion
    bulge_SED = galsim.SED('CWW_E_ext.sed', wave_type='ang', flux_type='flambda')
```

2023-11-27 21:57 UTC, beckermr commented on tests/test_deprecated.py
> +    np.testing.assert_array_equal(photon_array.dydz, 0.0)
```suggestion
    np.testing.assert_array_equal(photon_array.dydz, 0.)
```

2023-11-27 21:57 UTC, beckermr commented on tests/test_deprecated.py
> +    photon_array.wavelength = 500.0
```suggestion
    photon_array.wavelength = 500.
```

2023-11-27 21:57 UTC, beckermr commented on tests/test_deprecated.py
> +    np.testing.assert_array_equal(photon_array.dydz, 0.0)
```suggestion
    np.testing.assert_array_equal(photon_array.dydz, 0.)
```

2023-11-27 21:57 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion
    assert hsmp.max_moment_nsig2 == 0.
```

2023-11-27 21:57 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion
```

2023-11-27 21:58 UTC, beckermr commented on tests/test_deprecated.py
> +    expected_val = 1.0**3.0 / 3.0
```suggestion
    expected_val = 1.**3./3.
```

2023-11-27 21:58 UTC, beckermr commented on tests/test_deprecated.py
> +    np.testing.assert_almost_equal(rw.centroid.y, np.mean(pts[:, 1]))
```suggestion
    assert pts.shape == (npoints,2),"expected (%d,2) shape for points, got %s" % (npoints, pts.shape)
    np.testing.assert_almost_equal(rw.centroid.x, np.mean(pts[:,0]))
    np.testing.assert_almost_equal(rw.centroid.y, np.mean(pts[:,1]))
```

2023-11-27 21:59 UTC, beckermr commented on tests/test_deprecated.py
> +        )
```suggestion
        assert new_rw.npoints==rw.npoints,\
            "expected npoints=%d got %d" % (rw.npoints,new_rw.npoints)
```

2023-11-27 22:00 UTC, beckermr commented on tests/test_deprecated.py
> +        assert new_rw.npoints==rw.npoints,\
```suggestion
        assert new_rw.npoints == rw.npoints,\
```

2023-11-27 22:01 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion
        mess="expected input_half_light_radius=%.16g got %.16g"
        assert new_rw.input_half_light_radius == rw.input_half_light_radius,\
            mess % (rw.input_half_light_radius,new_rw.input_half_light_radius)
        assert new_rw.flux == rw.flux,\
            "expected flux=%.16g got %.16g" % (rw.flux,new_rw.flux)
```

2023-11-27 22:02 UTC, beckermr commented on tests/test_deprecated.py
> +        assert nobj == nobjc,"expected %d objects, got %d" % (nobj, nobjc)
```suggestion
        assert nobj==nobjc,"expected %d objects, got %d" % (nobj, nobjc)
```

2023-11-27 22:03 UTC, beckermr commented on tests/test_deprecated.py
> +        assert nobj==nobjc,"expected %d objects, got %d" % (nobj, nobjc)
```suggestion
        assert nobj==nobjc,"expected %d objects, got %d" % (nobj,nobjc)
```

2023-11-27 22:05 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion
        pts=rw.points
        ptsc=rwc.points
        assert (pts.shape == ptsc.shape),\
                "expected %s shape for points, got %s" % (pts.shape,ptsc.shape)
```

2023-11-27 22:05 UTC, beckermr commented on tests/test_deprecated.py
> +            "expected npoints==%d, got %d" % (rw.npoints,rwc.npoints)
```suggestion
            "expected npoints==%d, got %d" % (rw.npoints, rwc.npoints)
```

2023-11-27 22:06 UTC, beckermr commented on tests/test_deprecated.py
> +        assert wcs != wcs3, name + " is not != wcs.shiftOrigin(pos)"
```suggestion
        assert wcs != wcs3, name+' is not != wcs.shiftOrigin(pos)'
```

2023-11-27 22:06 UTC, beckermr commented on tests/test_deprecated.py
> +        assert wcs != wcs4, name + " is not != wcs.local()"
```suggestion
        assert wcs != wcs4, name+' is not != wcs.local()'
```

2023-11-27 22:06 UTC, beckermr commented on tests/test_deprecated.py
> +        assert wcs4 != wcs, name + " is not != wcs.local() (reverse)"
```suggestion
        assert wcs4 != wcs, name+' is not != wcs.local() (reverse)'
```

2023-11-27 22:06 UTC, beckermr commented on tests/test_deprecated.py
> +        world_pos1 = wcs.toWorld(galsim.PositionD(0, 0))
```suggestion
        world_pos1 = wcs.toWorld(galsim.PositionD(0,0))
```

2023-11-27 22:07 UTC, beckermr commented on tests/test_deprecated.py
> +    check_dep(__import__, "galsim.wfirst")
```suggestion
    check_dep(__import__, 'galsim.wfirst')
```

2023-11-27 22:08 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
    np.testing.assert_array_equal(galsim.wfirst.persistence_coefficients, 
                                  galsim.roman.persistence_coefficients)
    np.testing.assert_array_equal(galsim.wfirst.persistence_fermi_parameters,
                                  galsim.roman.persistence_fermi_parameters)
```

2023-11-27 22:08 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion
```

2023-11-27 22:08 UTC, beckermr commented on tests/test_deprecated.py
> +    """Test the deprecated high_accuracy and approximate_struts options."""
```suggestion
    """Test the deprecated high_accuracy and approximate_struts options.
    """
```

2023-11-27 22:09 UTC, beckermr commented on tests/test_deprecated.py
>      # Based on test_sensor.py:test_wavelengths_and_angles, but massively simplified.
```suggestion

    # Based on test_sensor.py:test_wavelengths_and_angles, but massively simplified.
```

2023-11-27 22:10 UTC, beckermr commented on tests/test_deprecated.py
> +    bandpass = galsim.Bandpass("LSST_i.dat", "nm").thin()
```suggestion
    sed = galsim.SED('CWW_E_ext.sed', 'nm', 'flambda').thin()
    bandpass = galsim.Bandpass('LSST_i.dat', 'nm').thin()
```

2023-11-27 22:10 UTC, beckermr commented on tests/test_deprecated.py
> +    im = galsim.Image(63, 63, scale=1)
```suggestion
    im = galsim.Image(63,63, scale=1)
```

2023-11-27 22:11 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
    check_dep(obj.drawImage, im, method="phot", surface_ops=[sampler, assigner], rng=rng,
              save_photons=True)
```

2023-11-27 22:11 UTC, beckermr commented on tests/test_deprecated.py
> +    """Test the basic functionality of the midpt() method."""
```suggestion
    """Test the basic functionality of the midpt() method.
    """
```

2023-11-27 22:11 UTC, beckermr commented on tests/test_deprecated.py
> +    x = 0.01 * np.arange(1000)
```suggestion
    x = 0.01*np.arange(1000)
```

2023-11-27 22:12 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
        result/expected_val, 1.0, decimal=2, verbose=True,
        err_msg='Simple test of midpt() method failed for f(x)=x^2 from 0 to 10')
```

2023-11-27 22:12 UTC, beckermr commented on tests/test_deprecated.py
> +    """Test the basic functionality of the trapz() method."""
```suggestion
    """Test the basic functionality of the trapz() method.
    """
```

2023-11-27 22:13 UTC, beckermr commented on tests/test_deprecated.py
> +    expected_val = 1.0**3.0 / 3.0
```suggestion
    expected_val = 1.**3./3.
```

2023-11-27 22:13 UTC, beckermr commented on tests/test_deprecated.py
> +    PSF = galsim.ChromaticAtmosphere(mono_PSF, base_wavelength=500,
```suggestion
    PSF = galsim.ChromaticAtmosphere(mono_PSF, base_wavelength=500,
```

2023-11-27 22:14 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
        result / expected_val, 1.0, decimal=6, verbose=True,
        err_msg='Test of trapz() with points failed for f(x)=x^2 from 0 to 1')
```

2023-11-27 22:15 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
        result/expected_val, 1.0, decimal=6, verbose=True,
        err_msg='Simple test of trapz() method failed for f(x)=x^2 from 0 to 1')
```

2023-11-27 22:15 UTC, beckermr commented on tests/test_deprecated.py
> +    )
```suggestion
    _, photons2 = check_dep(obj.drawPhot, image=im.copy(), surface_ops=[sampler, assigner], rng=rng)
```

2023-11-27 22:16 UTC, beckermr commented on tests/test_deprecated.py
> +    check_dep(obj.drawImage, im, method="phot", surface_ops=[sampler, assigner], rng=rng,
```suggestion
    check_dep(obj.drawImage, im, method='phot', surface_ops=[sampler, assigner], rng=rng,
```

2023-11-27 22:17 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion
        check_dep(galsim.roman.getPSF, SCA=use_sca, bandpass='Z087',
                            approximate_struts=False, high_accuracy=True,
                            wavelength='Z087')
```

2023-11-27 22:18 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion
                world_pos2.distanceTo(world_pos1) / galsim.arcsec, 0, 7,
                'shiftOrigin(new_origin) returned wrong world position')
```

2023-11-27 22:18 UTC, beckermr commented on tests/test_deprecated.py
> +        result / expected_val, 1.0, decimal=6, verbose=True,
```suggestion
        result/expected_val, 1.0, decimal=6, verbose=True,
```

2023-11-27 22:59 UTC, beckermr commented on tests/test_deprecated.py
> +        )
```suggestion
        assert rw.input_half_light_radius==rwc.input_half_light_radius,\
            "expected hlr==%g, got %g" % (rw.input_half_light_radius, rw.input_half_light_radius)
```

2023-11-27 23:00 UTC, beckermr commented on tests/test_deprecated.py
> +    ]
```suggestion
    wcs_list = [ galsim.OffsetWCS(0.3, galsim.PositionD(1,1), galsim.PositionD(10,23)),
                 galsim.OffsetShearWCS(0.23, galsim.Shear(g1=0.1,g2=0.3), galsim.PositionD(12,43)),
                 galsim.AffineTransform(0.01,0.26,-0.26,0.02, galsim.PositionD(12,43)),
                 galsim.UVFunction(ufunc = lambda x,y: 0.2*x, vfunc = lambda x,y: 0.2*y),
                 galsim.UVFunction(ufunc = lambda x,y: 0.2*x, vfunc = lambda x,y: 0.2*y,
                                   xfunc = lambda u,v: u / scale, yfunc = lambda u,v: v / scale),
                 galsim.UVFunction(ufunc='0.2*x + 0.03*y', vfunc='0.01*x + 0.2*y'),
               ]
```

2023-11-27 23:00 UTC, beckermr commented on tests/test_deprecated.py
> +        world_pos1 = wcs.toWorld(galsim.PositionD(0, 0), color=color)
```suggestion
                assert wcs == wcs2, name+' is not equal after wcs.local().withOrigin(origin)'
            wcs2 = wcs.local(wcs.origin, color=color).withOrigin(wcs.origin, wcs.world_origin)
            assert wcs == wcs2, name+' not equal after wcs.local().withOrigin(origin,world_origin)'
        world_pos1 = wcs.toWorld(galsim.PositionD(0,0), color=color)
```

2023-11-27 23:01 UTC, beckermr commented on tests/test_deprecated.py
> +        )
```suggestion
                world_pos2.x, world_pos1.x, 7,
                'withOrigin(new_origin) returned wrong world position')
```

2023-11-27 23:02 UTC, beckermr commented on tests/test_deprecated.py
> +        )
```suggestion
                world_pos2.y, world_pos1.y, 7,
                'withOrigin(new_origin) returned wrong world position')
```

2023-11-27 23:02 UTC, beckermr commented on tests/test_deprecated.py
> +        )
```suggestion
                world_pos3.x, new_world_origin.x, 7,
                'withOrigin(new_origin, new_world_origin) returned wrong position')
```

2023-11-27 23:03 UTC, beckermr commented on tests/test_deprecated.py
> +        )
```suggestion
                world_pos3.y, new_world_origin.y, 7,
                'withOrigin(new_origin, new_world_origin) returned wrong position')
```

2023-11-27 23:03 UTC, beckermr commented on tests/test_deprecated.py
> +    ]
```suggestion
    radec = lambda x,y: center.deproject_rad(cubic_u(x,y)*0.2, cubic_v(x,y)*0.2,
                                             projection='lambert')
    wcs_list = [ galsim.RaDecFunction(radec),
                 galsim.AstropyWCS('1904-66_TAN.fits', dir='fits_files'),
                 galsim.GSFitsWCS('tpv.fits', dir='fits_files'),
                 galsim.FitsWCS('sipsample.fits', dir='fits_files'),
               ]
```

2023-11-27 23:04 UTC, beckermr commented on tests/test_deprecated.py
> +        ({"approximate_struts": False, "high_accuracy": False}, {"pupil_bin": 4}),
```suggestion
        ({ 'approximate_struts':True, 'high_accuracy':False },
         { 'pupil_bin':8 }),
        ({ 'approximate_struts':True, 'high_accuracy':True },
         { 'pupil_bin':4, 'gsparams':galsim.GSParams(folding_threshold=2.e-3) }),
        ({ 'approximate_struts':False, 'high_accuracy':False },
         { 'pupil_bin':4 }),
```

2023-11-27 23:04 UTC, beckermr commented on tests/test_deprecated.py
> +            ),
```suggestion
            ({ 'approximate_struts':False, 'high_accuracy':True },
            { 'pupil_bin':1, 'gsparams':galsim.GSParams(folding_threshold=2.e-3) }),
```

2023-11-27 23:06 UTC, beckermr commented on tests/test_deprecated.py
> +
```suggestion
    d = check_dep(galsim.Delta, tol=1.e-2)
    assert d.gsparams.kvalue_accuracy == 1.e-2
    assert check_dep(getattr, d, 'tol') == d.gsparams.kvalue_accuracy
    n = check_dep(galsim.Nearest, tol=1.e-2)
    assert n.gsparams.kvalue_accuracy == 1.e-2
    assert check_dep(getattr, n, 'tol') == n.gsparams.kvalue_accuracy
    s = check_dep(galsim.SincInterpolant, tol=1.e-2)
    assert s.gsparams.kvalue_accuracy == 1.e-2
    assert check_dep(getattr, s, 'tol') == s.gsparams.kvalue_accuracy
    l = check_dep(galsim.Linear, tol=1.e-2)
    assert l.gsparams.kvalue_accuracy == 1.e-2
    assert check_dep(getattr, l, 'tol') == l.gsparams.kvalue_accuracy
    c = check_dep(galsim.Cubic, tol=1.e-2)
    assert c.gsparams.kvalue_accuracy == 1.e-2
    assert check_dep(getattr, c, 'tol') == c.gsparams.kvalue_accuracy
    q = check_dep(galsim.Quintic, tol=1.e-2)
    assert q.gsparams.kvalue_accuracy == 1.e-2
    assert check_dep(getattr, q, 'tol') == q.gsparams.kvalue_accuracy
    l3 = check_dep(galsim.Lanczos, 3, tol=1.e-2)
    assert l3.gsparams.kvalue_accuracy == 1.e-2
    assert check_dep(getattr, l3, 'tol') == l3.gsparams.kvalue_accuracy
    ldc = check_dep(galsim.Lanczos, 3, False, tol=1.e-2)
    assert ldc.gsparams.kvalue_accuracy == 1.e-2
    assert check_dep(getattr, ldc, 'tol') == ldc.gsparams.kvalue_accuracy
    l8 = check_dep(galsim.Lanczos, 8, tol=1.e-2)
    assert l8.gsparams.kvalue_accuracy == 1.e-2
    assert check_dep(getattr, l8, 'tol') == l8.gsparams.kvalue_accuracy
    l11 = check_dep(galsim.Interpolant.from_name, 'lanczos11', tol=1.e-2)
    assert l11.gsparams.kvalue_accuracy == 1.e-2
    assert check_dep(getattr, l11, 'tol') == l11.gsparams.kvalue_accuracy
```

2023-11-27 23:39 UTC, beckermr commented on tests/test_deprecated.py
> +    assert not photon_array.hasAllocatedAngles()
```suggestion
    if hasattr(galsim, "_galsim"):
        dxdz = check_dep(getattr, photon_array, 'dxdz')
        assert photon_array.hasAllocatedAngles()
    else:
        # jax-galsim always sets these additional properties
        # dxdz = check_dep(getattr, photon_array, 'dxdz')
        # however jax-galsim sets them to NaN so they are not allocated
        assert not photon_array.hasAllocatedAngles()
```

2023-11-27 23:40 UTC, beckermr commented on tests/test_deprecated.py
> +    # JAX-Galsim does not allow by reference setting - changed this
```suggestion
    assert hasattr(photon_array, "dydz")
    # JAX-Galsim does not allow by reference setting - changed this
```

2023-11-27 23:41 UTC, beckermr commented on tests/test_deprecated.py
> +    assert not photon_array.hasAllocatedWavelengths()
```suggestion
    if hasattr(galsim, "_galsim"):
        wave = check_dep(getattr, photon_array, 'wavelength')
        assert photon_array.hasAllocatedWavelengths()
    else:
        # jax-galsim always sets these additional properties
        # wave = check_dep(getattr, photon_array, 'wavelength')
        # however jax-galsim sets them to NaN so they are not allocated
        assert not photon_array.hasAllocatedWavelengths()
```

2023-11-27 23:43 UTC, beckermr commented on tests/test_deprecated.py
> +    assert not photon_array.hasAllocatedPupil()
```suggestion
    if hasattr(galsim, "_galsim"):
        u = check_dep(getattr, photon_array, 'pupil_u')
        assert photon_array.hasAllocatedPupil()
        assert len(photon_array.pupil_u) == nphotons
    else:
        # jax-galsim always sets these additional properties
        # u = check_dep(getattr, photon_array, "pupil_u")
        # however jax-galsim sets them to NaN so they are not allocated
        assert not photon_array.hasAllocatedPupil()
```

2023-11-27 23:44 UTC, beckermr commented on tests/test_deprecated.py
> +    # JAX-Galsim does not allow by reference setting - changed this
```suggestion
    assert hasattr(photon_array, "pupil_v")
    # JAX-Galsim does not allow by reference setting - changed this
```

2023-11-27 23:44 UTC, beckermr commented on tests/test_deprecated.py
>      assert len(photon_array.time) == nphotons
```suggestion
    if hasattr(galsim, "_galsim"):
        t = check_dep(getattr, photon_array, 'time')
        assert photon_array.hasAllocatedTimes()    
    else:
        # jax-galsim always sets these additional properties
        # t = check_dep(getattr, photon_array, "time")
        # however jax-galsim sets them to NaN so they are not allocated
        assert not photon_array.hasAllocatedTimes()
        assert len(photon_array.time) == nphotons
```

2023-11-27 23:46 UTC, beckermr commented on tests/test_deprecated.py
>      np.testing.assert_array_equal(photon_array.time, 0.0)
```suggestion
    assert len(photon_array.time) == nphotons
    np.testing.assert_array_equal(photon_array.time, 0.0)
```

2023-11-27 23:46 UTC, beckermr commented on tests/test_deprecated.py
> +    assert not photon_array.hasAllocatedAngles()
```suggestion
    if hasattr(galsim, "_galsim"):
        dydz = check_dep(getattr, photon_array, 'dydz')
        assert photon_array.hasAllocatedAngles()
    else:
        # jax-galsim always sets these additional properties
        # dydz = check_dep(getattr, photon_array, "dydz")
        # however jax-galsim sets them to NaN so they are not allocated
        assert not photon_array.hasAllocatedAngles()
```

2023-11-27 23:47 UTC, beckermr commented on tests/test_deprecated.py
> +    # JAX-Galsim does not allow by reference setting - changed this
```suggestion
    assert hasattr(photon_array, "dxdz")
    # JAX-Galsim does not allow by reference setting - changed this
```

2023-11-27 23:49 UTC, beckermr commented on tests/test_deprecated.py
> +    assert not photon_array.hasAllocatedPupil()
```suggestion
    if hasattr(galsim, "_galsim"):
        v = check_dep(getattr, photon_array, 'pupil_v')
        assert photon_array.hasAllocatedPupil()
        assert len(photon_array.pupil_u) == nphotons    
    else:
        # jax-galsim always sets these additional properties
        # v = check_dep(getattr, photon_array, "pupil_v")
        # however jax-galsim sets them to NaN so they are not allocated
        assert not photon_array.hasAllocatedPupil()
```

2024-08-22 16:02 UTC, beckermr commented on tests/galsim_test_helpers.py
> +            (not hasattr(galsim, "_galsim"))
```suggestion
            is_jax_galsim()
```

2024-08-22 16:02 UTC, beckermr commented on tests/galsim_test_helpers.py
> +            (not hasattr(galsim, "_galsim"))
```suggestion
            is_jax_galsim()
```

2024-08-22 16:03 UTC, beckermr commented on tests/galsim_test_helpers.py
> +    rtol *= 3
```suggestion
    if is_jax_galsim():
        rtol *= 3
```

2024-08-22 16:07 UTC, beckermr commented on tests/test_celestial_galsim.py
> +        assert_raises(TypeError,galsim.AngleUnit, 'spam')
```suggestion
    assert_raises((ValueError, TypeError), galsim.AngleUnit, 'spam')
```

2024-08-22 16:08 UTC, beckermr commented on tests/test_celestial_galsim.py
> +        assert_raises(TypeError,galsim.Angle, 'spam', galsim.degrees)
```suggestion
    assert_raises((ValueError, TypeError), galsim.AngleUnit, 'spam'))
```

2024-08-22 16:08 UTC, beckermr commented on tests/test_celestial_galsim.py
> +        center.rad,
```suggestion
        center.rad,
        rtol=0,
        atol=1e-16,        
```

2024-08-22 16:09 UTC, beckermr commented on tests/test_celestial_galsim.py
> +        center.rad,
```suggestion
        center.rad,
        rtol=0,
        atol=1e-16,
```

2024-08-22 16:09 UTC, beckermr commented on tests/test_celestial_galsim.py
> +        center.rad,
```suggestion
        center.rad,
        rtol=0,
        atol=1e-16,
```

2024-08-22 16:09 UTC, beckermr commented on tests/test_celestial_galsim.py
> +        center.rad,
```suggestion
        center.rad,
        rtol=0,
        atol=1e-16,
```

2024-08-22 16:10 UTC, beckermr commented on tests/test_celestial_galsim.py
> +    assert_raises((ValueError, TypeError), galsim.AngleUnit, 'spam'))
```suggestion
    assert_raises((ValueError, TypeError), galsim.Angle, 'spam'))
```

2024-08-22 16:12 UTC, beckermr commented on tests/test_celestial_galsim.py
> +    assert_raises((ValueError, TypeError), galsim.Angle, 'spam'))
```suggestion
    assert_raises((ValueError, TypeError), galsim.Angle, 'spam')
```

2024-08-22 16:33 UTC, beckermr commented on tests/test_optics.py
> +        im._array = im.array.at[x**2+y**2 < 230**2].set(1.0)
```suggestion
    if is_jax_galsim():
        # no refs in jax-galsim
        im._array = im.array.at[x**2+y**2 < 230**2].set(1.0)
    else:
        im.array[x**2+y**2 < 230**2] = 1.0
```

2024-08-22 17:06 UTC, beckermr commented on tests/test_exponential.py
> +    np.testing.assert_allclose(photons2.flux, photons.flux)
```suggestion
    if is_jax_galsim():
        np.testing.assert_allclose(photons2.x, photons.x)
        np.testing.assert_allclose(photons2.y, photons.y)
        np.testing.assert_allclose(photons2.flux, photons.flux)
    else:
        assert photons2 == photons, "Exponential makePhot not equivalent to drawPhot"
```

2024-08-22 17:09 UTC, beckermr commented on tests/test_moffat.py
> +        np.testing.assert_allclose(psf.maxk, 11.634597424960159, atol=0, rtol=0.2)
```suggestion
    if is_jax_galsim():
        np.testing.assert_array_almost_equal(psf.maxk, 11.634597424960159, atol=0, rtol=0.2)
    else:
        np.testing.assert_array_almost_equal(psf.maxk, 11.634597424960159)
```

2024-08-22 17:09 UTC, beckermr commented on tests/test_moffat.py
> +        np.testing.assert_allclose(psf.maxk, 11.634597424960159, atol=0, rtol=0.2)
```suggestion
    if is_jax_galsim():
        np.testing.assert_array_almost_equal(psf.maxk, 11.634597424960159, atol=0, rtol=0.2)
    else:
        np.testing.assert_array_almost_equal(psf.maxk, 11.634597424960159)
```

2024-08-22 17:10 UTC, beckermr commented on tests/test_moffat.py
> +                rtol = 5e-3
```suggestion
            if is_jax_galsim():
                rtol = 5e-3
            else:
                rtol = 1.e-7 if psf.trunc == 0 else 3.e-3
```

2024-08-22 19:44 UTC, beckermr commented on tests/test_deprecated.py
> +        photon_array.wavelength = 500.0
```suggestion
        photon_array.wavelength = 500.0
        # jax-galsim is allocated now
        assert photon_array.hasAllocatedWavelengths()
```

2024-08-22 19:47 UTC, beckermr commented on tests/test_deprecated.py
> +        # jax-galsim is allocated now
```suggestion
        # jax-galsim is allocated now
        assert photon_array.hasAllocatedTimes()
```

2024-08-22 19:57 UTC, beckermr commented on tests/test_deprecated.py
> +        photon_array.dydz = 0.59
```suggestion
        photon_array.dydz = 0.59
        # non-nan means allocated for jax-galsim
        assert photon_array.hasAllocatedAngles()
```

2024-08-22 19:57 UTC, beckermr commented on tests/test_deprecated.py
> +        photon_array.pupil_v = 10.0
```suggestion
        photon_array.pupil_v = 10.0
        # jax-galsim is allocated now
        assert photon_array.hasAllocatedPupil()
```

2024-10-14 23:13 UTC, rmjarvis requested changes

2024-10-14 23:13 UTC, rmjarvis commented on tests/test_shear.py
> +        assert_raises(galsim.GalSimRangeError,galsim.Shear,e1=0.7,e2=0.9)
What does JaxGalSim do with these inputs?  They don't define valid Shear values.

2024-10-14 23:13 UTC, rmjarvis commented on tests/test_utilities.py
> +        pass
I think I can guess what it does with floats.  But I'm quite curious what it does with "blue".

2024-10-14 23:13 UTC, rmjarvis commented on tests/test_utilities.py
> +        pass
What does it do for an undefined Bounds if you ask for the center?

2024-10-14 23:13 UTC, rmjarvis commented on tests/test_utilities.py
> +    img1 = galsim.utilities.interleaveImages(im_list,8,offsets)
This is fine I guess, but I'm curious why this was required?

2024-10-14 23:13 UTC, rmjarvis commented on tests/test_wcs.py
> +    wcs3 = wcs.shiftOrigin(new_origin)
For a LocalWCS, these are equivalent.  And IMO withOrigin is preferred, since the WCS doesn't have an origin yet.

2024-10-14 23:13 UTC, rmjarvis commented on tests/test_zernike.py
> +        Z1 = galsim.zernike.Zernike([0]*(j1+1)+[1], R_outer=R_outer)
Again, why add the extra boilerplate?

2026-03-25 13:07 UTC, closed without merging

2026-05-12 09:45 UTC, beckermr commented on tests/galsim_test_helpers.py
> +        rtol *= 3
This was due to bug. Has now been fixed! Thanks for flagging!

2026-05-12 09:46 UTC, beckermr commented on tests/test_interpolatedimage.py
> +            assert np.isclose(ln.kval(x[12]), true_kval[12])
This was due to jax-galsim using a slightly less accurate interpolation method (akima vs natural cubic spline). This is now fixed.

2026-05-12 09:47 UTC, beckermr commented on tests/test_moffat.py
> +        np.testing.assert_allclose(psf.maxk, 11.634597424960159, atol=0, rtol=0.2)
We removed the `trunc` option in jax-galsim, so this change is no longer relevant.

2026-05-12 09:52 UTC, beckermr commented on tests/test_random.py
> +        assert a != b
So jax-galsim doesn't have DistDeviate implement and so doesn't pass the test below. jax-galsim RNG seeds are short and so includes them in the repr.

2026-05-12 09:56 UTC, beckermr commented on tests/test_random.py
> +        pass
It returns -1 for every call. That's fun.

```
In [6]: pd()
Out[6]: Array(-1., dtype=float32)

In [7]: pd()
Out[7]: Array(-1., dtype=float32)

In [8]: pd()
Out[8]: Array(-1., dtype=float32)

In [9]: pd()
Out[9]: Array(-1., dtype=float32)
```

xref: https://github.com/GalSim-developers/JAX-GalSim/issues/237

2026-05-12 10:00 UTC, beckermr commented on tests/test_celestial_galsim.py
> +    assert_raises((ValueError, TypeError), galsim.Angle, 'spam')
fixed.

2026-05-12 10:08 UTC, beckermr commented on tests/test_celestial_galsim.py
> +    )
The code here follows galsim/coord exactly. So I think this is due to the precise way in which jax does the computation. Under JIT, things can get reordered and simplified. I did not track this down further than that speculation.

2026-05-12 10:15 UTC, beckermr commented on tests/galsim_test_helpers.py
> +                                         '%s negative flux drawReal is not negative of +flux image'%name)
They are not for jax arrays at least. It raises this error:

```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

2026-05-12 10:17 UTC, beckermr commented on tests/test_draw.py
> +
This is now fixed.

2026-05-12 10:18 UTC, beckermr commented on tests/test_draw.py
> +        Nfft = 1536
This is now fixed.

2026-05-12 10:30 UTC, beckermr commented on tests/test_draw.py
> +        pass
Interesting, this change is not needed when jax-galsim is working in float32 as opposed to float64.

2026-05-12 15:07 UTC, beckermr commented on tests/test_draw.py
> +        pass
Fixed here: https://github.com/GalSim-developers/JAX-GalSim/pull/238

2026-05-12 15:32 UTC, beckermr commented on tests/test_image.py
> +                    assert im2(x,y) != value
That is a better default. I will make the change.

2026-05-12 15:34 UTC, beckermr commented on tests/test_utilities.py
> +    img1 = galsim.utilities.interleaveImages(im_list,8,offsets)
To run the galsim test suite with jax-galsim, we basically patch `galsim` top `jax_galsim` globally in all modules. The local import here bypassed that patching.

2026-05-12 15:34 UTC, beckermr commented on tests/test_utilities.py
> +    img1 = galsim.utilities.interleaveImages(im_list,8,offsets)
Or at least that is what I remember happening...

2026-05-12 15:34 UTC, beckermr commented on tests/test_zernike.py
> +        Z1 = galsim.zernike.Zernike([0]*(j1+1)+[1], R_outer=R_outer)
This change was related to the global patching of modules for running the tests with jax_galsim IIRC.

2026-05-12 15:40 UTC, beckermr commented on tests/test_draw.py
> +        pass
There are a few things happening here:

- Once a function is JITed, you cannot raise python-based warnings or errors. Some libraries like equinox have utilities to help with this, which would be an option.
- In order to use JIT or autodiff, JAX will trace the execution path of the function. The tracers are abstract things that hold basic pieces of information like array shapes, dtypes, etc, but do not hold a specific value for the array. So we cannot check their values and raise for disallowed values.
- As a result of the previous item, one cannot branch in a function based on a JAX array's value. This precludes many of the data checks.

We have an open issue for this here: https://github.com/GalSim-developers/JAX-GalSim/issues/237

2026-05-12 16:00 UTC, beckermr commented on tests/test_image.py
> +                    assert im2(x,y) != value
xref: https://github.com/GalSim-developers/JAX-GalSim/pull/239

2026-05-12 22:08 UTC, beckermr commented on tests/test_image.py
> +        assert im(11,19) == 20
This test is skipped now due to views not being supported.

2026-05-13 10:23 UTC, beckermr commented on tests/test_draw.py
> +        pass
It is that we don't warn if they are invalid values.

2026-05-13 10:38 UTC, beckermr commented on tests/test_deprecated.py
> +        check_dep(galsim.GSParams, small_fraction_of_flux=1.e-6)
xref: https://github.com/GalSim-developers/GalSim-for-JAX-GalSim-Testing/pull/13

2026-05-13 10:47 UTC, beckermr commented on tests/test_draw.py
> +            np.testing.assert_array_almost_equal(xim.array, xim2.array)
xref: https://github.com/GalSim-developers/GalSim-for-JAX-GalSim-Testing/pull/13

2026-05-13 10:47 UTC, beckermr commented on tests/test_draw.py
> +            np.testing.assert_array_almost_equal(kim.array, kim2.array)
xref: https://github.com/GalSim-developers/GalSim-for-JAX-GalSim-Testing/pull/13

2026-05-13 10:50 UTC, beckermr commented on tests/test_interpolatedimage.py
> +        pass
https://github.com/GalSim-developers/GalSim-for-JAX-GalSim-Testing/pull/13

2026-05-13 10:52 UTC, beckermr commented on tests/test_photon_array.py
> +        pa1.flux[0:50] = photon_array.flux[:50]
xref: https://github.com/GalSim-developers/GalSim-for-JAX-GalSim-Testing/pull/13

2026-05-13 10:56 UTC, beckermr commented on tests/test_moffat.py
> +    np.testing.assert_array_almost_equal(psf.xValue(cen), psf.max_sb)
jax-galsim no longer supports truncated moffat profiles. so I removed this change. xref: https://github.com/GalSim-developers/GalSim-for-JAX-GalSim-Testing/pull/13

2026-05-13 11:00 UTC, beckermr commented on tests/test_wcs.py
> +    wcs3 = wcs.shiftOrigin(new_origin)
xref: https://github.com/GalSim-developers/GalSim-for-JAX-GalSim-Testing/pull/13

2026-05-13 13:18 UTC, beckermr commented on tests/test_exponential.py
> +        assert photons2 == photons, "Exponential makePhot not equivalent to drawPhot"
They are. Changing back: https://github.com/GalSim-developers/GalSim-for-JAX-GalSim-Testing/pull/14

2026-05-13 16:12 UTC, beckermr commented on tests/test_utilities.py
> +        pass
It raises a type error. 

```
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

2026-05-13 16:17 UTC, beckermr commented on tests/test_utilities.py
> +        pass
This now raises the correct error.

2026-05-13 16:30 UTC, beckermr commented on tests/test_shear.py
> +        assert_raises(galsim.GalSimRangeError,galsim.Shear,e1=0.7,e2=0.9)
It creates NaNs. 

```
In [1]: import jax_galsim

In [2]: s = jax_galsim.Shear(e1=0.7,e2=0.9)

In [3]: s
Out[3]: galsim.Shear(nan)

In [4]: s.e1
Out[4]: Array(nan, dtype=float32, weak_type=True)

In [5]: s.e2
Out[5]: Array(nan, dtype=float32, weak_type=True)

In [6]: s.g1
Out[6]: Array(nan, dtype=float32, weak_type=True)

In [7]: s.g2
Out[7]: Array(nan, dtype=float32, weak_type=True)

```

That is not as good as a raising an error, but is good enough. The NaNs will be noticed for sure and jax has decent utilities for tracking them down.

2026-05-13 16:34 UTC, beckermr commented on tests/test_photon_array.py
> +        pass
Yes. JAX itself raises

```
In [3]: photon_array.x[:] = 5
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 photon_array.x[:] = 5

File ~/mambaforge/envs/jax-galsim/lib/python3.13/site-packages/jax/_src/numpy/array_methods.py:622, in _unimplemented_setitem(self, i, x)
    618 def _unimplemented_setitem(self, i, x):
    619   msg = ("JAX arrays are immutable and do not support in-place item assignment."
    620          " Instead of x[idx] = y, use x = x.at[idx].set(y) or another .at[] method:"
    621          " https://docs.jax.dev/en/latest/_autosummary/jax.numpy.ndarray.at.html")
--> 622   raise TypeError(msg.format(type(self)))

TypeError: JAX arrays are immutable and do not support in-place item assignment. Instead of x[idx] = y, use x = x.at[idx].set(y) or another .at[] method: https://docs.jax.dev/en/latest/_autosummary/jax.numpy.ndarray.at.html
```

2026-05-13 16:43 UTC, beckermr commented on tests/test_photon_array.py
> +        pass
In JAX, no. Out of bounds indices generally do not raise. Here are the available behaviors: 

```
string specifying out-of-bound indexing mode. Options are:

"promise_in_bounds": (default) The user promises that indices are in bounds. No additional checking will be performed. In practice, this means that out-of-bounds indices in get() will be clipped, and out-of-bounds indices in set(), add(), etc. will be dropped.

"clip": clamp out of bounds indices into valid range.

"drop": ignore out-of-bound indices.

"fill": alias for "drop". For get(), the optional fill_value argument specifies the value that will be returned.
```

2026-05-13 18:19 UTC, beckermr commented on tests/test_draw.py
> +        np.testing.assert_array_almost_equal(image2.array, image1.array, decimal=12)
xref: https://github.com/GalSim-developers/GalSim/pull/1360

2026-05-13 18:19 UTC, beckermr commented on tests/test_draw.py
> +        image1 = galsim.ImageF(32,32, init_value=100)
xref: https://github.com/GalSim-developers/GalSim/pull/1360

2026-05-13 18:19 UTC, beckermr commented on tests/test_noise.py
> +            var, big_vgn.var_image.array.mean(), decimal,
xref: https://github.com/GalSim-developers/GalSim/pull/1360

2026-05-13 18:27 UTC, beckermr commented
OK @rmjarvis I addressed all of the comments here. Thanks a bunch for the review! It definitely helped improve JAX-GalSim and helped to flush out at least one bug.